### ISSUE TITLE
Which packet has sender's domain information ?

### ISSUE THREAD

**Issue by victormarcus** [tachtler/jilter-InfoMilter#4]
Hi Klaus,

I can see the domain information comes in SMFIC_HELO and SMFIC_MACRO. Which of them has the sender domain and receiver domain?

**Comment by tachtler** [comment]
Hi Abhishek,

you can see the DEBUG output inside README.md under: LOG-File output.

Greetings
Klaus.

**Comment by victormarcus** [comment]
Hi Klaus,

Yes, I can see the debug output. But in this case, both sender and receivers are from test.example.com domain. What if sender is from test.xxxx.com. What I am asking is, 
In `properties.getProperty("j") `  and  `helohost` which carries the sender domain and which carries receiver's ?

Regards,
Kumbhaj

**Comment by tachtler** [comment]
Hi Abhishek,

the HELO/EHLO is the MTA.

For example, HELO could be mx1.nausch.org and sender (mail from:) could be klaus@tachtler.net.

(mx1.nausch.org is my Backup MX :-) )

```
properties.getProperty("j")
```
is the HELO/EHLO MTA, because it's inside the "connect", before the mail from: and the rcpt to: was reached.

Greetings
Klaus
